{
 "title": "Guider Output Visualization",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "content": "<h1><center>Guider Output Visualization - 1st AWS Instance</center></h1>"
  },
  {
   "title": "CPU Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "woojin_ncloude" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "db_host_server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "woojin_ncloude" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "db_host_server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "kernel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "woojin_ncloude" },
      { "condition": "OR", "key": "host", "operator": "=", "value": "db_host_server" }
     ]
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ],
      [
       { "params": [ "anon" ], "type": "field" }
      ],
      [
       { "params": [ "kernel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "inbound" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "outbound" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "block",
     "select": [
      [
       { "params": [ "ioWait" ], "type": "field" }
      ],
      [
       { "params": [ "nrFault" ], "type": "field" }
      ],
      [
       { "params": [ "read" ], "type": "field" }
      ],
      [
       { "params": [ "write" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "task",
     "select": [
      [
       { "params": [ "nrThread" ], "type": "field" }
      ],
      [
       { "params": [ "nrBlocked" ], "type": "field" }
      ],
      [
       { "params": [ "nrCtx" ], "type": "field" }
      ],
      [
       { "params": [ "nrProc" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage Best 3",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "rank1_comm" ], "type": "field" }
      ],
      [
       { "params": [ "rank1_rss" ], "type": "field" }
      ],
      [
       { "params": [ "rank2_comm" ], "type": "field" }
      ],
      [
       { "params": [ "rank2_rss" ], "type": "field" }
      ],
      [
       { "params": [ "rank3_comm" ], "type": "field" }
      ],
      [
       { "params": [ "rank3_rss" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}