.TH Guider "1" "February 2023" "Performance Analysis Tool"
.SH NAME
guider \- Comprehensive Performance Analyzer
.SH SYNOPSIS
.B guider
[\,--help\/] COMMAND [\,OPTIONS\/\fR]
.SH FEATURES
Guider provides you with everything you need to measure, analyze, and verify your system's performance with features like monitoring, profiling, tracing, visualization, control, logging, networking, testing, and utilities,
.PP
.SH EXAMPLES
.TP
guider help
Print guider command list
.TP
guider COMMAND -h
Print options and examples of COMMAND
.TP
guider top -a
Print resource usage on system
.TP
guider top -a -o guider.out
Collect resource usage on system and report it to guider.out file
.SH AUTHOR
Written by Peace Lee
.SH "REPORTING BUGS"
https://github.com/iipeace/guider/issues
.br
.SH COPYRIGHT
License GPLv2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>.
.SH "SEE ALSO"
.br
https://github.com/iipeace/guider
.br
