#!/bin/sh

# Guider Launcher
#
# Copyright (c) 2016-2026 Peace Lee <iipeace5@gmail.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.

# export CMDLINE for Guider #
export CMDLINE=$0

# check PYTHON variable #
if [ -n "$PYTHON" ]; then
    exec "$PYTHON" -m guider "$@"
fi

# define PYTHON variable #
PYTHON=""

# check python binaries #
for cmd in python3 python
do
    # check a python binary #
    command -v "$cmd" > /dev/null 2>&1 || continue

    # set available python list #
    PYTHON="$PYTHON$cmd "

    # check guider module #
    if ! "$cmd" -c "import guider" 2>/dev/null; then
        continue
    fi

    # launch Guider #
    exec "$cmd" -m guider "$@"
done

# print error message #
if [ -z "$PYTHON" ]; then
    echo "[Error] failed to find python"
else
    echo "[Error] failed to find Guider module in $PYTHON"
fi
exit 1
