{
 "title": "Guider Output Visualization",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "content": "<h1><center>Guider Output Visualization</center></h1>"
  },
  {
   "title": "CPU Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "kernel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "kernel" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "anon" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "input" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "output" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "block",
     "select": [
      [
       { "params": [ "ioWait" ], "type": "field" }
      ],
      [
       { "params": [ "nrFault" ], "type": "field" }
      ],
      [
       { "params": [ "read" ], "type": "field" }
      ],
      [
       { "params": [ "write" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "task",
     "select": [
      [
       { "params": [ "nrThread" ], "type": "field" }
      ],
      [
       { "params": [ "nrBlocked" ], "type": "field" }
      ],
      [
       { "params": [ "nrCtx" ], "type": "field" }
      ],
      [
       { "params": [ "nrProc" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}