"""
guider_catalog.py — Command metadata catalog for Guider MCP integration.

Each entry defines execution constraints, output type, and MCP tool mapping.
"""

# ---------------------------------------------------------------------------
# Schema fields:
#   requires_root   bool   — needs CAP_SYS_ADMIN / CAP_BPF / root
#   output_type     str    — "json" | "text" | "file"
#   streaming       bool   — True = infinite loop; adapter MUST add -R Ns
#   default_duration str   — default -R value for streaming commands
#   min_kernel      str    — minimum Linux kernel version ("" = any)
#   mcp_tool        str    — which of the 10 MCP tools handles this command
#   semaphore       bool   — True = tracefs; max 1 concurrent
#   android_only    bool   — requires Android/adb
#   description     str    — one-line description
#   examples        list   — usage examples
# ---------------------------------------------------------------------------

CATALOG: dict = {
    # ------------------------------------------------------------------ #
    #  systemMonitor                                                       #
    # ------------------------------------------------------------------ #
    "top": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "System-wide CPU/memory/IO top monitor",
        "examples": ["guider top", "guider top -i 1 -R 5s -J"],
    },
    "ttop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Thread-level CPU top monitor",
        "examples": ["guider ttop", "guider ttop -i 1 -R 5s"],
    },
    "atop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "App-level resource monitor",
        "examples": ["guider atop"],
    },
    "mtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Memory usage top monitor",
        "examples": ["guider mtop"],
    },
    "vtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Virtual memory top monitor",
        "examples": ["guider vtop"],
    },
    "wtop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Wait/blocked state thread monitor",
        "examples": ["guider wtop"],
    },
    "ftop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "File descriptor top monitor",
        "examples": ["guider ftop"],
    },
    "ntop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Network usage top monitor",
        "examples": ["guider ntop"],
    },
    "disktop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Disk I/O top monitor",
        "examples": ["guider disktop"],
    },
    "irqtop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "IRQ usage top monitor",
        "examples": ["guider irqtop"],
    },
    "swaptop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Swap usage top monitor",
        "examples": ["guider swaptop"],
    },
    "slabtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Kernel slab allocator top monitor",
        "examples": ["guider slabtop"],
    },
    "kstop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Kernel thread top monitor",
        "examples": ["guider kstop"],
    },
    "stacktop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Stack usage top monitor",
        "examples": ["guider stacktop"],
    },
    "ctop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Container/cgroup resource top monitor",
        "examples": ["guider ctop"],
    },
    "cgtop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Cgroup top monitor",
        "examples": ["guider cgtop"],
    },
    "contop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Container top monitor",
        "examples": ["guider contop"],
    },
    "oomtop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "OOM candidate top monitor",
        "examples": ["guider oomtop"],
    },
    "pytop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Python process top monitor",
        "examples": ["guider pytop"],
    },
    "rtop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Remote system top monitor (via hserver)",
        "examples": ["guider rtop"],
    },
    "sigtop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "systemMonitor",
        "semaphore": False,
        "android_only": False,
        "description": "Signal delivery top monitor",
        "examples": ["guider sigtop"],
    },
    "dbustop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "D-Bus message top monitor",
        "examples": ["guider dbustop"],
    },

    # ------------------------------------------------------------------ #
    #  bpfTrace                                                            #
    # ------------------------------------------------------------------ #
    "bpftop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Per-TID BPF function call count (delta/interval)",
        "examples": ["guider bpftop do_sys_open", "guider bpftop -q LAT"],
    },
    "bpfsnoop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Real-time per-function call stream via BPF perf ring buffer",
        "examples": ["guider bpfsnoop do_sys_open"],
    },
    "bpfstacktop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "CPU on-stack sampler at 99Hz (SW_CPU_CLOCK)",
        "examples": ["guider bpfstacktop"],
    },
    "bpfwaittop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Off-CPU blocked stack sampler via sched_switch tracepoint",
        "examples": ["guider bpfwaittop"],
    },
    "bpfblktop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Block I/O latency attribution via block_rq_issue/complete",
        "examples": ["guider bpfblktop"],
    },
    "bpfrunqtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Runqueue latency histogram via sched_wakeup+sched_switch",
        "examples": ["guider bpfrunqtop"],
    },
    "bpfreclaimtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Memory direct reclaim latency per stack via mm_vmscan tracepoints",
        "examples": ["guider bpfreclaimtop"],
    },
    "bpftcpretrans": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "TCP retransmit attribution per flow via tcp_retransmit_skb",
        "examples": ["guider bpftcpretrans"],
    },
    "bpfdroptop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Packet drop attribution by kernel stack via kfree_skb kprobe",
        "examples": ["guider bpfdroptop"],
    },
    "bpftcplat": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "TCP RTT latency histogram (log2 ns) via tcp_probe tracepoint",
        "examples": ["guider bpftcplat"],
    },
    "bpflocktop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Futex/lock contention latency per stack via futex_wait kprobe",
        "examples": ["guider bpflocktop"],
    },
    "bpfbinderlat": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": True,
        "description": "Binder caller blocking latency + kernel/user stack",
        "examples": ["guider bpfbinderlat"],
    },
    "bpfbindersnoop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": True,
        "description": "Real-time Binder transaction stream via binder_transaction tracepoint",
        "examples": ["guider bpfbindersnoop"],
    },
    "bpfbinderpool": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": True,
        "description": "Binder thread pool sync/async utilization monitor",
        "examples": ["guider bpfbinderpool"],
    },
    "bpfsyscalltop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Per-syscall latency stats (elapsed/count/err/min/max/avg)",
        "examples": ["guider bpfsyscalltop"],
    },
    "bpfsyscallsnoop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Real-time per-syscall event stream with arguments",
        "examples": ["guider bpfsyscallsnoop", "guider bpfsyscallsnoop -q ADDUSERSTACK"],
    },
    "bpfpkttop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "XDP top network flows: per-5-tuple pkt/byte delta per interval",
        "examples": ["guider bpfpkttop"],
    },
    "bpfpktsnoop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "XDP packet stream: real-time per-packet metadata",
        "examples": ["guider bpfpktsnoop"],
    },
    "bpfnetlat": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "XDP→socket receive latency histogram",
        "examples": ["guider bpfnetlat"],
    },
    "bpfwatch": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "HW watchpoint streaming via perf ring buffer",
        "examples": ["guider bpfwatch <addr>"],
    },
    "bpfwatchtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "HW watchpoint access top monitor",
        "examples": ["guider bpfwatchtop <addr>"],
    },
    "bpfwqtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Workqueue task latency top monitor",
        "examples": ["guider bpfwqtop"],
    },
    "bpfcachetop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Page cache hit/miss top monitor",
        "examples": ["guider bpfcachetop"],
    },
    "bpfkleaktop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Kernel memory leak detection top",
        "examples": ["guider bpfkleaktop"],
    },
    "bpflsmopen": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "LSM hook open event monitor",
        "examples": ["guider bpflsmopen"],
    },
    "bpfprogtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "BPF program runtime monitoring (all loaded programs)",
        "examples": ["guider bpfprogtop"],
    },
    "irqlattop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "bpfTrace",
        "semaphore": False,
        "android_only": False,
        "description": "Per-IRQ handler latency histograms via tracepoints",
        "examples": ["guider irqlattop"],
    },

    # ------------------------------------------------------------------ #
    #  ftraceProfile                                                       #
    # ------------------------------------------------------------------ #
    "trtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "Tracepoint event top via tracefs",
        "examples": ["guider trtop sched/*", "guider trtop irq/*"],
    },
    "tptop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "Tracepoint top monitor",
        "examples": ["guider tptop"],
    },
    "bpfmarktop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "5.8",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "BPF mark-based profiling top",
        "examples": ["guider bpfmarktop"],
    },
    "funcrec": {
        "requires_root": True,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "Function call recording via ftrace function_graph",
        "examples": ["guider funcrec -e task_name"],
    },
    "btop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "Function block top via ftrace",
        "examples": ["guider btop"],
    },
    "utop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "ftraceProfile",
        "semaphore": False,
        "android_only": False,
        "description": "User-space function top (perf + addr2line)",
        "examples": ["guider utop -e <pid>"],
    },
    "ktop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "Kernel function top via ftrace",
        "examples": ["guider ktop"],
    },
    "ptop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "ftraceProfile",
        "semaphore": False,
        "android_only": False,
        "description": "Perf event sampling top",
        "examples": ["guider ptop"],
    },
    "fperf": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "ftraceProfile",
        "semaphore": False,
        "android_only": False,
        "description": "Function-level perf profiling (requires target via -e <pid>)",
        "examples": ["guider fperf -e <pid>"],
    },
    "utrace": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "ftraceProfile",
        "semaphore": False,
        "android_only": False,
        "description": "User-space call trace recording",
        "examples": ["guider utrace -e <pid>"],
    },
    "btrace": {
        "requires_root": True,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "Kernel function call trace recording via ftrace",
        "examples": ["guider btrace -e task_name"],
    },
    "iorec": {
        "requires_root": True,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "Block I/O recording via ftrace",
        "examples": ["guider iorec"],
    },
    "filerec": {
        "requires_root": True,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "File system event recording via ftrace",
        "examples": ["guider filerec"],
    },
    "sysrec": {
        "requires_root": True,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "4.4",
        "mcp_tool": "ftraceProfile",
        "semaphore": True,
        "android_only": False,
        "description": "System call recording via ftrace",
        "examples": ["guider sysrec"],
    },
    "stat": {
        "requires_root": False,
        "output_type": "json",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "ftraceProfile",
        "semaphore": False,
        "android_only": False,
        "description": "System statistics snapshot",
        "examples": ["guider stat"],
    },

    # ------------------------------------------------------------------ #
    #  networkTrace                                                        #
    # ------------------------------------------------------------------ #
    "bpftcplife": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "5.8",
        "mcp_tool": "networkTrace",
        "semaphore": False,
        "android_only": False,
        "description": "TCP connection lifecycle events (connect/accept/close)",
        "examples": ["guider bpftcplife"],
    },

    # ------------------------------------------------------------------ #
    #  androidPerf                                                         #
    # ------------------------------------------------------------------ #
    "perfetto": {
        "requires_root": False,
        "output_type": "json",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android Perfetto trace capture and analysis",
        "examples": ["guider perfetto -q PERF:5s", "guider perfetto -I trace.pb"],
    },
    "bdtop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android Binder transaction top monitor",
        "examples": ["guider bdtop"],
    },
    "attop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android ATrace event top monitor",
        "examples": ["guider attop"],
    },
    "gfxtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android GPU/graphics frame top monitor",
        "examples": ["guider gfxtop"],
    },
    "andtop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android system top monitor",
        "examples": ["guider andtop"],
    },
    "bugrec": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android bug report capture",
        "examples": ["guider bugrec"],
    },
    "mdtop": {
        "requires_root": True,
        "output_type": "json",
        "streaming": True,
        "default_duration": "5s",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android media/codec top monitor",
        "examples": ["guider mdtop"],
    },
    "andcmd": {
        "requires_root": False,
        "output_type": "text",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Run Android-specific diagnostic commands",
        "examples": ["guider andcmd getselinux", "guider andcmd getpkglist", "guider andcmd getproclist"],
    },
    "hprof": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android Java heap profiling via HPROF",
        "examples": ["guider hprof -e <pid>"],
    },
    "scrcap": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android screen capture",
        "examples": ["guider scrcap"],
    },
    "logand": {
        "requires_root": False,
        "output_type": "text",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": True,
        "description": "Android logcat stream",
        "examples": ["guider logand -q FILTER:tag"],
    },
    "cantop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": False,
        "description": "CAN bus signal top monitor",
        "examples": ["guider cantop vcan0"],
    },
    "cansnoop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "",
        "mcp_tool": "androidPerf",
        "semaphore": False,
        "android_only": False,
        "description": "CAN bus real-time per-frame streaming",
        "examples": ["guider cansnoop vcan0"],
    },

    # ------------------------------------------------------------------ #
    #  memoryAnalyze                                                       #
    # ------------------------------------------------------------------ #
    "checkdup": {
        "requires_root": True,
        "output_type": "json",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "memoryAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Detect duplicate memory mappings across processes",
        "examples": ["guider checkdup", "guider checkdup -q SKIPEXMAPPED"],
    },
    "leaktop": {
        "requires_root": False,
        "output_type": "json",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "",
        "mcp_tool": "memoryAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "User-space memory leak tracking top",
        "examples": ["guider leaktop -e <pid>"],
    },
    "leaktrace": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "memoryAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Memory allocation trace for leak analysis",
        "examples": ["guider leaktrace -e <pid>"],
    },
    "mtrace": {
        "requires_root": False,
        "output_type": "json",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "memoryAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Memory trace and analysis",
        "examples": ["guider mtrace -e <pid>"],
    },
    "dump": {
        "requires_root": False,
        "output_type": "json",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "memoryAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Process memory dump snapshot",
        "examples": ["guider dump -e <pid>"],
    },

    # ------------------------------------------------------------------ #
    #  visualize                                                           #
    # ------------------------------------------------------------------ #
    "draw": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw performance graph from recorded data file",
        "examples": ["guider draw -I report.out"],
    },
    "drawtime": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw time-series graph from recorded data",
        "examples": ["guider drawtime -I report.out"],
    },
    "drawcpu": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw CPU usage graph",
        "examples": ["guider drawcpu -I report.out"],
    },
    "drawmem": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw memory usage graph",
        "examples": ["guider drawmem -I report.out"],
    },
    "drawnet": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw network usage graph",
        "examples": ["guider drawnet -I report.out"],
    },
    "drawdisk": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw disk I/O graph",
        "examples": ["guider drawdisk -I report.out"],
    },
    "drawflame": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw flame graph from stack data",
        "examples": ["guider drawflame -I stacks.out"],
    },
    "drawflamediff": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw differential flame graph",
        "examples": ["guider drawflamediff -I before.out -q AFTER:after.out"],
    },
    "drawscatter": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw scatter plot from data",
        "examples": ["guider drawscatter -I data.out"],
    },
    "drawhist": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw histogram from data",
        "examples": ["guider drawhist -I data.out"],
    },
    "drawviolin": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw violin plot from data",
        "examples": ["guider drawviolin -I data.out"],
    },
    "drawstack": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw stacked area chart from data",
        "examples": ["guider drawstack -I data.out"],
    },
    "drawbitmap": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw bitmap representation of data",
        "examples": ["guider drawbitmap -I data.out"],
    },
    "drawconn": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw connection/flow graph",
        "examples": ["guider drawconn -I data.out"],
    },
    "drawpsi": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw PSI (Pressure Stall Information) graph",
        "examples": ["guider drawpsi -I data.out"],
    },
    "drawreq": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw request latency graph",
        "examples": ["guider drawreq -I data.out"],
    },
    "drawrss": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw RSS (Resident Set Size) memory graph",
        "examples": ["guider drawrss -I data.out"],
    },
    "drawgantt": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw Gantt chart from timeline data",
        "examples": ["guider drawgantt -I data.out"],
    },
    "drawdiff": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Draw diff comparison graph between two datasets",
        "examples": ["guider drawdiff -I before.out -q AFTER:after.out"],
    },
    "convert": {
        "requires_root": False,
        "output_type": "file",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "visualize",
        "semaphore": False,
        "android_only": False,
        "description": "Convert guider output file to another format",
        "examples": ["guider convert -I data.out"],
    },

    # ------------------------------------------------------------------ #
    #  logAnalyze                                                          #
    # ------------------------------------------------------------------ #
    "logkmsg": {
        "requires_root": False,
        "output_type": "text",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Kernel message log streaming (dmesg-like)",
        "examples": ["guider logkmsg"],
    },
    "logdlt": {
        "requires_root": False,
        "output_type": "text",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "DLT (Diagnostic Log and Trace) log streaming",
        "examples": ["guider logdlt"],
    },
    "logjrl": {
        "requires_root": False,
        "output_type": "text",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Journald log streaming",
        "examples": ["guider logjrl"],
    },
    "logsys": {
        "requires_root": False,
        "output_type": "text",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "System log streaming",
        "examples": ["guider logsys"],
    },
    "logtrace": {
        "requires_root": True,
        "output_type": "text",
        "streaming": True,
        "default_duration": "10s",
        "min_kernel": "4.4",
        "mcp_tool": "logAnalyze",
        "semaphore": True,
        "android_only": False,
        "description": "ftrace event log streaming",
        "examples": ["guider logtrace"],
    },
    "convlog": {
        "requires_root": False,
        "output_type": "json",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Convert log files to structured format",
        "examples": ["guider convlog -I log.txt"],
    },
    "printand": {
        "requires_root": False,
        "output_type": "text",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": True,
        "description": "Print Android log file",
        "examples": ["guider printand -I logcat.txt"],
    },
    "printkmsg": {
        "requires_root": False,
        "output_type": "text",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Print kernel message log file",
        "examples": ["guider printkmsg -I kmsg.txt"],
    },
    "printdlt": {
        "requires_root": False,
        "output_type": "text",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Print DLT log file",
        "examples": ["guider printdlt -I trace.dlt"],
    },
    "printjrl": {
        "requires_root": False,
        "output_type": "text",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Print journald log file",
        "examples": ["guider printjrl -I journal.log"],
    },
    "printtrace": {
        "requires_root": False,
        "output_type": "text",
        "streaming": False,
        "default_duration": "",
        "min_kernel": "",
        "mcp_tool": "logAnalyze",
        "semaphore": False,
        "android_only": False,
        "description": "Print trace file",
        "examples": ["guider printtrace -I trace.out"],
    },
}

# ---------------------------------------------------------------------------
# Commands that are BLOCKED from MCP exposure
# ---------------------------------------------------------------------------
BLOCKED_COMMANDS: set = {
    # System control / destructive
    "kill", "tkill", "freeze", "pause", "hook", "cgroup",
    "swapout", "limitcpu", "limitcpuset", "limitmem",
    "limitread", "limitwrite", "setafnt", "setcpu",
    "setsched", "setprop", "sysrq", "exec",
    # LLM loop prevention
    "ask", "chat", "embed", "rag",
    "askai", "askrun", "aiperiodic",
}

# ---------------------------------------------------------------------------
# Extra -q options that are BLOCKED for security
# ---------------------------------------------------------------------------
BLOCKED_OPTS: set = {
    # LLM loop
    "ASKAI", "ASKRUN", "AIPERIODIC", "LLMPROVIDER", "LLMMODEL",
    # Command execution
    "EXITCMD", "PRINTCMD",
    # File manipulation
    "DUPOUTPATH", "OUTFILEUSER", "OUTFILEPERM",
}


# Pre-built index: mcp_tool → list of command names (built once at import time)
_TOOL_COMMANDS: dict = {}
for _cmd, _meta in CATALOG.items():
    _TOOL_COMMANDS.setdefault(_meta["mcp_tool"], []).append(_cmd)


def get_tool_commands(mcp_tool: str) -> list:
    """Return all command names assigned to the given MCP tool (O(1) lookup)."""
    return _TOOL_COMMANDS.get(mcp_tool, [])


def get_catalog_entry(command: str) -> dict | None:
    """Return metadata for a command, or None if unknown/blocked."""
    if command in BLOCKED_COMMANDS:
        return None
    return CATALOG.get(command)
